/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_yawk_snap_YawkatSnapNatives */

#ifndef _Included_at_yawk_snap_YawkatSnapNatives
#define _Included_at_yawk_snap_YawkatSnapNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_yawk_snap_YawkatSnapNatives
 * Method:    isKeyPressed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_at_yawk_snap_YawkatSnapNatives_isKeyPressed
  (JNIEnv *, jclass, jint);

/*
 * Class:     at_yawk_snap_YawkatSnapNatives
 * Method:    checkAutoStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_yawk_snap_YawkatSnapNatives_checkAutoStart
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     at_yawk_snap_YawkatSnapNatives
 * Method:    setAutoStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_yawk_snap_YawkatSnapNatives_setAutoStart
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     at_yawk_snap_YawkatSnapNatives
 * Method:    unsetAutoStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_yawk_snap_YawkatSnapNatives_unsetAutoStart
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
